name: Social Feed Generator

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install feedgenerator feedparser playwright
        playwright install firefox

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push RSS feed
      run: |
        git config user.name "rss-bot"
        git config user.email "rss-bot@example.com"
        git add social_feed.xml
        git commit -m "Update social feed"
        git push
