name: Social Feed Scraper

on:
  schedule:
    - cron: "*/30 * * * *"    # every 30 minutes
  workflow_dispatch: {}      # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3) Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Install Playwright browser dependencies
      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      # 5) Run scraper script
      - name: Run scraper.py
        run: python scraper.py

      # 6) Commit and push RSS feed if changed
      - name: Commit and push RSS feed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "rss-bot"
          git config user.email "rss-bot@users.noreply.github.com"

          if ! git diff --quiet social_feed.xml; then
            git add social_feed.xml
            git commit -m "Auto-update social_feed.xml"
            git push origin HEAD:main
          else
            echo "No changes to social_feed.xml; skipping commit."
