name: Social Feed Scraper

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      - name: Run scraper.py
        run: python scraper.py

      - name: Commit and push RSS feed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "rss-bot"
          git config user.email "rss-bot@users.noreply.github.com"

          if ! git diff --quiet social_feed.xml; then
            git add social_feed.xml
            git commit -m "Auto-update social_feed.xml"
            git push origin HEAD:main
          else
            echo "No changes to social_feed.xml; skipping commit."
