name: Merge MLB & FlashLive Schedule

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date for schedule in YYYY-MM-DD (defaults to today)'
        required: false

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug: show workflow source
        run: |
          echo "==== Contents of this workflow ===="
          sed -n '1,200p' .github/workflows/merge-mlb-flashlive.yml
          echo "==================================="

      - name: Pick DATE
        id: pick_date
        run: |
          if [[ -n "${{ github.event.inputs.date }}" ]]; then
            echo "Using input date: ${{ github.event.inputs.date }}"
            echo "date=${{ github.event.inputs.date }}" >> "$GITHUB_OUTPUT"
          else
            TODAY=$(date +'%Y-%m-%d')
            echo "No input provided; defaulting to $TODAY"
            echo "date=$TODAY" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Debug: show workspace layout
        run: |
          echo "Working dir: $(pwd)"
          ls -R .

      - name: Run merge script
        run: |
          echo "Running merge_mlb_flashlive.py for date ${{ steps.pick_date.outputs.date }}"
          python merge_mlb_flashlive.py --date "${{ steps.pick_date.outputs.date }}"
          echo "---- After script ----"
          ls -lh *.json || echo "❌ No JSON files generated"

      - name: Commit & push results
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.json
          echo "Staged files:"
          git diff --cached --name-only || true
          git commit -m "Add merged schedule for ${{ steps.pick_date.outputs.date }}" || echo "No changes to commit"
          git push
