# .github/workflows/merge-mlb-flashlive.yml
name: Merge MLB & FlashLive Schedule

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to scrape (YYYY-MM-DD). Leave blank for today.'
        required: false
        default: ''

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine DATE
        id: pick-date
        run: |
          if [ -n "${{ github.event.inputs.date }}" ]; then
            echo "Using manual input date: ${{ github.event.inputs.date }}"
            echo "DATE=${{ github.event.inputs.date }}" >> $GITHUB_ENV
          else
            TODAY=$(date --utc +'%Y-%m-%d')
            echo "No date input; defaulting to today: $TODAY"
            echo "DATE=$TODAY" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run merge script
        run: |
          python merge_mlb_flashlive.py --date "$DATE"

      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mlb_flashlive_merged.json
          git diff --quiet || git commit -m "Merge MLB+FlashLive schedule for $DATE"
          git push
