name: Merge MLB & FlashLive Schedule

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to fetch (YYYY-MM-DD). Defaults to today if omitted.'
        required: false

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pick DATE
        run: |
          if [ -n "${{ github.event.inputs.date }}" ]; then
            echo "DATE=${{ github.event.inputs.date }}" >> $GITHUB_ENV
          else
            echo "DATE=$(date +%F)" >> $GITHUB_ENV
          fi

      - name: Show DATE
        run: echo "→ DATE = $DATE"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run merge script
        run: python merge_mlb_flashlive.py --date "$DATE"

      - name: Debug: List files & preview merged JSON
        run: |
          echo "=== Runner file tree (top 2 levels) ==="
          find . -maxdepth 2 -type f
          echo
          echo "=== mlb_flashlive_merged.json head (first 20 lines) ==="
          if [ -f mlb_flashlive_merged.json ]; then
            head -n 20 mlb_flashlive_merged.json
          else
            echo ">>> FILE NOT FOUND at $(pwd)/mlb_flashlive_merged.json <<<"
          fi

      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mlb_flashlive_merged.json
          git commit -m "Merge MLB+FlashLive schedule for $DATE" || echo "Nothing to commit"
          git push
