# .github/workflows/merge-mlb-flashlive.yml
name: Merge MLB & FlashLive Schedule

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'YYYY-MM-DD to fetch (defaults to today)'
        required: false

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # … rest of your steps …


      - name: Pick DATE
        run: |
          if [ -n "${{ github.event.inputs.date }}" ]; then
            echo "DATE=${{ github.event.inputs.date }}" >> $GITHUB_ENV
          else
            echo "DATE=$(date -u +%F)" >> $GITHUB_ENV
          fi

      - name: Debug: list workflows directory
        run: |
          echo "Workflows in repo:"
          ls -R .github/workflows

      # ... rest of your steps here ...
