name: Run Sports Scraper

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: python run.py

      - name: Commit and push debug data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # always add the debug file
          git add data/flash_debug.json
          # only commit if there's something new
          if ! git diff --cached --quiet; then
            git commit -m "Update flash_debug.json"
            git push
          else
            echo "No changes in flash_debug.json to commit"
          fi


