name: Merge MLB & FlashLive Schedule

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to fetch (YYYY-MM-DD). Defaults to today (UTC) if omitted.'
        required: false

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pick DATE
        run: |
          if [ -n "${{ github.event.inputs.date }}" ]; then
            echo "DATE=${{ github.event.inputs.date }}" >> $GITHUB_ENV
          else
            echo "DATE=$(date -u +%F)" >> $GITHUB_ENV
          fi

      - name: Show DATE
        run: echo "→ DATE = $DATE"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run merge script
        run: python merge_mlb_flashlive.py --date "$DATE"

      - name: Debug: list files & preview output
        run: |
          echo "Filesystem snapshot:"
          find . -maxdepth 2 -type f
          echo
          echo "Preview merged JSON:"
          head -n 20 mlb_flashlive_merged.json || echo "(file not found)"

      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add mlb_flashlive_merged.json
          git commit -m "Merge MLB+FlashLive schedule for $DATE" || echo "No changes to commit"
          git push
