name: Scrape WNBA Schedule

on:
  workflow_dispatch:
    inputs:
      league:
        description: 'League slug to scrape'
        required: true
        default: 'wnba'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run WNBA scraper
        run: |
          mkdir -p artifacts
          python livesports_scraper.py ${{ github.event.inputs.league }} \
            > artifacts/${{ github.event.inputs.league }}_schedule.json

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.league }}_schedule
          path: artifacts/${{ github.event.inputs.league }}_schedule.json
