name: Social Feed Scraper

on:
  schedule:
    - cron: "*/30 * * * *"     # run every 30 minutes
  workflow_dispatch: {}       # also allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Set up Python 3.x
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # 4) Run the scraper
      - name: Run scraper.py
        run: python scraper.py

      # 5) Commit & push social_feed.xml if changed
      - name: Commit and push RSS feed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "rss-bot"
          git config user.email "rss-bot@users.noreply.github.com"

          # Only commit if social_feed.xml was updated
          if ! git diff --quiet social_feed.xml; then
            git add social_feed.xml
            git commit -m "Auto-update social_feed.xml"
            git push origin HEAD:main
          else
            echo "No changes to social_feed.xml; skipping commit."
          fi
