name: Social Feed JSON Scraper

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push JSON feed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "json-bot"
          git config user.email "json-bot@users.noreply.github.com"

          if ! git diff --quiet social_feed.json; then
            git add social_feed.json
            git commit -m "Auto-update social_feed.json"
            git push origin HEAD:main
          else
            echo "No changes to social_feed.json; skipping commit."
